check_ingraph: Fix xmlrpclib.Fault: <Fault 1: "<type 'exceptions.AttributeError'>:'NoneType' object has no attribute 'interval'">
Remove hardcoded interval from getPlotValues2 calls since the interval may not exist.
Further the daemon automatically determines the best fitting interval when unset.